### ISSUE TITLE
Error trying to add the pakage in Julia v0.6

### ISSUE THREAD

**Issue by 4lrdyD** [gaika/AutoDiffSource.jl#17]
the error I get is the following: 
ERROR: GitError(Code:ENOTFOUND, Class:Reference, Revspec 'HEAD' not found.)
macro expansion at .\libgit2\error.jl:99 [inlined]
Base.LibGit2.GitTree(::Base.LibGit2.GitRepo, ::String) at .\libgit2\repository.jl:116
#isdiff#76(::Bool, ::Function, ::Base.LibGit2.GitRepo, ::String, ::String) at .\libgit2\libgit2.jl:147
(::Base.LibGit2.#kw##isdiff)(::Array{Any,1}, ::Base.LibGit2.#isdiff, ::Base.LibGit2.GitRepo, ::String, ::String) at .\<missing>:0
(::Base.Pkg.Read.##5#6{String})(::Base.LibGit2.GitRepo) at .\pkg\read.jl:184
with(::Base.Pkg.Read.##5#6{String}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:608
requires_path(::String, ::Dict{VersionNumber,Base.Pkg.Types.Available}) at .\pkg\read.jl:183
fixed(::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Set{String}, ::VersionNumber) at .\pkg\read.jl:229
fixed(::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}) at .\pkg\read.jl:225
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where N) at .\pkg\entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at .\task.jl:335
Stacktrace:
 [1] sync_end() at .\task.jl:287
 [2] macro expansion at .\task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at .\pkg\dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at .\file.jl:59
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at .\pkg\dir.jl:36
 [7] add(::String) at .\pkg\pkg.jl:117

**Comment by gaika** [comment]
wow, network error? libgit bug? what happens if you remove the package and try to add it again?

**Comment by 4lrdyD** [comment]
@gaika the package is not yet installed, or what package do you mean?

**Comment by gaika** [comment]
can you try it again, it must have been some github glitch, it sure works fine now.

**Comment by 4lrdyD** [comment]
I tried to install it several times, but I get the same error

**Comment by gaika** [comment]
Seems like it is from https://github.com/JuliaLang/julia/issues/17994

**Comment by 4lrdyD** [comment]
I followed lobingera's steps at https://github.com/JuliaLang/julia/issues/23858 and I was able to install AutoDiffSource. i'm not sure but according to #17994 I should not use Pkg.free to avoid this problem.

**Comment by 4lrdyD** [comment]
i followed lobingera's steps at https://github.com/JuliaLang/julia/issues/23858 and i was able to install AutoDiffSource. I'm not sure but according to JuliaLang/julia#17994 I should not use Pkg.free to avoid this problem.

**Comment by NinoRode** [comment]
Same problems as @4lrdyD, same solution. But Ubuntu Bionic and Julia 0.6.2 and a year later. Does somebody know what is going on?
